# Generated by Django 5.0.2 on 2024-06-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0001_initial"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="library.book",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
