# Generated by Django 5.0.2 on 2024-06-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_transaction_book_transaction_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_book_transaction",
            field=models.BooleanField(default=False),
        ),
    ]
